### ISSUE TITLE
White login page after new installation

### ISSUE THREAD

**Issue by pat75007** [thilinah/icehrm#10]
Hi there,

I installed icehrm v9.1 on a Linux box (SLES 11 SP3, Apache 2.2.12, PHP 5.3, MySQL 5.5.39). Every thing is alright but i have a white login page. 
No error within the icehrm.log (r/w rights are ok). 
No error within the Apache log. 

Any idea ? 
Patrice

**Comment by thilinah** [comment]
Try commenting out first line which is error_reporting(E_ERROR);

in include.common.php.

Also make sure the log path provided in app/config.php is writable by your
webserver. Then check that error log for more details.

On Fri, Feb 20, 2015 at 4:47 PM, pat75007 <notifications@github.com> wrote:

> Hi there,
>
> I installed icehrm v9.1 on a Linux box (SLES 11 SP3, Apache 2.2.12, PHP
> 5.3, MySQL 5.5.39). Every thing is alright but i have a white login page.
> No error within the icehrm.log (r/w rights are ok).
> No error within the Apache log.
>
> Any idea ?
> Patrice
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thilinah/icehrm/issues/10>.
>



-- 
Thilina Hasantha
TP: +94 722 33 67 47
http://lk.linkedin.com/in/thilinah

**Comment by pat75007** [comment]
Ok, i have an error message :
Warning: require(): Unable to find the wrapper "phar" - did you forget to
enable it when you configured PHP? in
/srv/www/vhosts/icehrm_v9.1/lib/aws.phar on line 3 Warning: require():
Unable to find the wrapper "phar" - did you forget to enable it when you
configured PHP? in /srv/www/vhosts/icehrm_v9.1/lib/aws.phar on line 3
Warning: require(phar://aws.phar/aws-autoloader.php): failed to open
stream: No such file or directory in
/srv/www/vhosts/icehrm_v9.1/lib/aws.phar on line 3 Fatal error: require():
Failed opening required 'phar://aws.phar/aws-autoloader.php'
(include_path='.:/usr/share/php5:/usr/share/php5/PEAR') in
/srv/www/vhosts/icehrm_v9.1/lib/aws.phar on line 3


2015-02-20 12:29 GMT+01:00 Thilina Hasantha <notifications@github.com>:

**Comment by pat75007** [comment]
Ok, PHAR is installed. No i have : 
Fatal error: Can't use method return value in write context in /srv/www/vhosts/icehrm_v9.1/classes/S3FileSystem.php on line 38

**Comment by thilinah** [comment]
Applied a fix for this in master branch, please replacing the file.
https://github.com/thilinah/icehrm/commit/636e970041ad495f34dabffbe016fd471002470a

On Fri, Feb 20, 2015 at 5:28 PM, pat75007 <notifications@github.com> wrote:

> Ok, PHAR is installed. No i have :
> Fatal error: Can't use method return value in write context in
> /srv/www/vhosts/icehrm_v9.1/classes/S3FileSystem.php on line 38
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thilinah/icehrm/issues/10#issuecomment-75227596>.
>



-- 
Thilina Hasantha
TP: +94 722 33 67 47
http://lk.linkedin.com/in/thilinah

**Comment by pat75007** [comment]
I have applied the fix. I have the login page but it cant find some ressources : 
<img src="<?=$logoFileUrl?>">
Or : 
<link href="<?=BASE_URL?>bootstrap/css/bootstrap.css" rel="stylesheet">

Any idea ? 
The file app/config.php is ok. 

Patrice
