### ISSUE TITLE
There is a mysterious 0 on the top left corner during installation

### ISSUE THREAD

**Issue by rhnvrm** [thilinah/icehrm#21]
![image](https://cloud.githubusercontent.com/assets/952036/8015660/27e2e0d4-0bf8-11e5-9ab3-610070a0c9e1.png)

**Comment by circuitmamu** [comment]
open the app/install/index.php

go to line number 14 and remove the echo from there
echo fwrite($file,"");
replace to 
fwrite($file,"");

**Comment by thilinah** [comment]
Merged, you are welcome to add more iprovements
