### ISSUE TITLE
Data employee and etc not show v12.6

### ISSUE THREAD

**Issue by zhiephie** [thilinah/icehrm#28]
I'm try this software and problem click page employee and etc, 
detect error in firebug : SyntaxError: expected expression, got '<'

**Comment by thilinah** [comment]
Please try uncommenting, second line of include.common.php in icehrm root

Currently it will lokk like 

<?php
//error_reporting(0);

Please change it to

<?php
error_reporting(0);


The reason for this issue is that our web server is printing notices on web page

**Comment by zhiephie** [comment]
oh okay, thanks u
